---
engines:
  eslint:
    enabled: true
  scss-lint:
    enabled: true
    checks:
      HexLength:
        enabled: false
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.scss"
  - "**.md"
exclude_paths:
- "docs/"
- "**.html"
- "**.json"
- "src/styles/vendor/"
- "src/styles/fonts/"
